
# cargo-vet config file

[cargo-vet]
version = "0.10"

[[exemptions.aho-corasick]]
version = "1.1.4"
criteria = "safe-to-deploy"

[[exemptions.alloca]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.anes]]
version = "0.1.6"
criteria = "safe-to-run"

[[exemptions.anstream]]
version = "0.6.21"
criteria = "safe-to-deploy"

[[exemptions.anstyle]]
version = "1.0.13"
criteria = "safe-to-deploy"

[[exemptions.anstyle-parse]]
version = "0.2.7"
criteria = "safe-to-deploy"

[[exemptions.anstyle-query]]
version = "1.1.5"
criteria = "safe-to-deploy"

[[exemptions.anstyle-wincon]]
version = "3.0.11"
criteria = "safe-to-deploy"

[[exemptions.assert_cmd]]
version = "2.1.2"
criteria = "safe-to-run"

[[exemptions.autocfg]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "2.10.0"
criteria = "safe-to-run"

[[exemptions.bstr]]
version = "1.12.1"
criteria = "safe-to-run"

[[exemptions.bumpalo]]
version = "3.19.1"
criteria = "safe-to-run"

[[exemptions.cast]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.cc]]
version = "1.2.55"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.4"
criteria = "safe-to-run"

[[exemptions.ciborium]]
version = "0.2.2"
criteria = "safe-to-run"

[[exemptions.ciborium-io]]
version = "0.2.2"
criteria = "safe-to-run"

[[exemptions.ciborium-ll]]
version = "0.2.2"
criteria = "safe-to-run"

[[exemptions.clap]]
version = "4.5.59"
criteria = "safe-to-deploy"

[[exemptions.clap_builder]]
version = "4.5.59"
criteria = "safe-to-deploy"

[[exemptions.clap_derive]]
version = "4.5.55"
criteria = "safe-to-deploy"

[[exemptions.clap_lex]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.colorchoice]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.console]]
version = "0.15.11"
criteria = "safe-to-run"

[[exemptions.criterion]]
version = "0.8.2"
criteria = "safe-to-run"

[[exemptions.criterion-plot]]
version = "0.8.2"
criteria = "safe-to-run"

[[exemptions.crossbeam-deque]]
version = "0.8.6"
criteria = "safe-to-run"

[[exemptions.crossbeam-epoch]]
version = "0.9.18"
criteria = "safe-to-run"

[[exemptions.crossbeam-utils]]
version = "0.8.21"
criteria = "safe-to-run"

[[exemptions.crunchy]]
version = "0.2.4"
criteria = "safe-to-run"

[[exemptions.difflib]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.either]]
version = "1.15.0"
criteria = "safe-to-run"

[[exemptions.encode_unicode]]
version = "1.0.0"
criteria = "safe-to-run"

[[exemptions.equivalent]]
version = "1.0.2"
criteria = "safe-to-run"

[[exemptions.errno]]
version = "0.3.14"
criteria = "safe-to-run"

[[exemptions.fastrand]]
version = "2.3.0"
criteria = "safe-to-run"

[[exemptions.find-msvc-tools]]
version = "0.1.9"
criteria = "safe-to-deploy"

[[exemptions.float-cmp]]
version = "0.10.0"
criteria = "safe-to-run"

[[exemptions.getrandom]]
version = "0.3.4"
criteria = "safe-to-run"

[[exemptions.glob]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.half]]
version = "2.7.1"
criteria = "safe-to-run"

[[exemptions.hashbrown]]
version = "0.16.1"
criteria = "safe-to-run"

[[exemptions.heck]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "2.13.0"
criteria = "safe-to-run"

[[exemptions.indoc]]
version = "2.0.7"
criteria = "safe-to-deploy"

[[exemptions.insta]]
version = "1.46.3"
criteria = "safe-to-run"

[[exemptions.is_terminal_polyfill]]
version = "1.70.2"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.13.0"
criteria = "safe-to-run"

[[exemptions.itoa]]
version = "1.0.17"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.85"
criteria = "safe-to-run"

[[exemptions.libc]]
version = "0.2.180"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.11.0"
criteria = "safe-to-run"

[[exemptions.memchr]]
version = "2.7.6"
criteria = "safe-to-deploy"

[[exemptions.memoffset]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.normalize-line-endings]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.num-traits]]
version = "0.2.19"
criteria = "safe-to-run"

[[exemptions.once_cell]]
version = "1.21.3"
criteria = "safe-to-deploy"

[[exemptions.once_cell_polyfill]]
version = "1.70.2"
criteria = "safe-to-deploy"

[[exemptions.oorandom]]
version = "11.1.5"
criteria = "safe-to-run"

[[exemptions.page_size]]
version = "0.6.0"
criteria = "safe-to-run"

[[exemptions.plotters]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-backend]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-svg]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.portable-atomic]]
version = "1.13.0"
criteria = "safe-to-deploy"

[[exemptions.predicates]]
version = "3.1.4"
criteria = "safe-to-run"

[[exemptions.predicates-core]]
version = "1.0.9"
criteria = "safe-to-run"

[[exemptions.predicates-tree]]
version = "1.0.12"
criteria = "safe-to-run"

[[exemptions.proc-macro2]]
version = "1.0.106"
criteria = "safe-to-deploy"

[[exemptions.pyo3]]
version = "0.28.2"
criteria = "safe-to-deploy"

[[exemptions.pyo3-build-config]]
version = "0.28.2"
criteria = "safe-to-deploy"

[[exemptions.pyo3-ffi]]
version = "0.28.2"
criteria = "safe-to-deploy"

[[exemptions.pyo3-macros]]
version = "0.28.2"
criteria = "safe-to-deploy"

[[exemptions.pyo3-macros-backend]]
version = "0.28.2"
criteria = "safe-to-deploy"

[[exemptions.python3-dll-a]]
version = "0.2.14"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.44"
criteria = "safe-to-deploy"

[[exemptions.r-efi]]
version = "5.3.0"
criteria = "safe-to-run"

[[exemptions.rayon]]
version = "1.11.0"
criteria = "safe-to-run"

[[exemptions.rayon-core]]
version = "1.13.0"
criteria = "safe-to-run"

[[exemptions.regex]]
version = "1.12.3"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.4.13"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.8.8"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "1.1.3"
criteria = "safe-to-run"

[[exemptions.rustversion]]
version = "1.0.22"
criteria = "safe-to-deploy"

[[exemptions.same-file]]
version = "1.0.6"
criteria = "safe-to-run"

[[exemptions.serde]]
version = "1.0.228"
criteria = "safe-to-deploy"

[[exemptions.serde_core]]
version = "1.0.228"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.228"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.149"
criteria = "safe-to-deploy"

[[exemptions.serde_spanned]]
version = "1.0.4"
criteria = "safe-to-run"

[[exemptions.shlex]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.similar]]
version = "2.7.0"
criteria = "safe-to-run"

[[exemptions.strsim]]
version = "0.11.1"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.114"
criteria = "safe-to-deploy"

[[exemptions.target-lexicon]]
version = "0.13.4"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.25.0"
criteria = "safe-to-run"

[[exemptions.termtree]]
version = "0.5.1"
criteria = "safe-to-run"

[[exemptions.tinytemplate]]
version = "1.2.1"
criteria = "safe-to-run"

[[exemptions.toml]]
version = "1.0.3+spec-1.1.0"
criteria = "safe-to-run"

[[exemptions.toml_datetime]]
version = "1.0.0+spec-1.1.0"
criteria = "safe-to-run"

[[exemptions.toml_parser]]
version = "1.0.9+spec-1.1.0"
criteria = "safe-to-run"

[[exemptions.toml_writer]]
version = "1.0.6+spec-1.1.0"
criteria = "safe-to-run"

[[exemptions.unicode-ident]]
version = "1.0.22"
criteria = "safe-to-deploy"

[[exemptions.unindent]]
version = "0.2.4"
criteria = "safe-to-deploy"

[[exemptions.utf8parse]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.wait-timeout]]
version = "0.2.1"
criteria = "safe-to-run"

[[exemptions.walkdir]]
version = "2.5.0"
criteria = "safe-to-run"

[[exemptions.wasip2]]
version = "1.0.2+wasi-0.2.9"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen]]
version = "0.2.108"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.108"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.108"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.108"
criteria = "safe-to-run"

[[exemptions.web-sys]]
version = "0.3.85"
criteria = "safe-to-run"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-run"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.winapi-util]]
version = "0.1.11"
criteria = "safe-to-run"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.windows-link]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.59.0"
criteria = "safe-to-run"

[[exemptions.windows-sys]]
version = "0.61.2"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_i686_gnu]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_i686_msvc]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.winnow]]
version = "0.7.14"
criteria = "safe-to-run"

[[exemptions.wit-bindgen]]
version = "0.51.0"
criteria = "safe-to-run"

[[exemptions.zerocopy]]
version = "0.8.37"
criteria = "safe-to-run"

[[exemptions.zerocopy-derive]]
version = "0.8.37"
criteria = "safe-to-run"

[[exemptions.zmij]]
version = "1.0.17"
criteria = "safe-to-deploy"
